spring:
  application:
    name: dou-rss-producer

  threads:
    virtual:
      enabled: true

  config:
    import:
      - optional:file:.env[.properties]
      - classpath:redis.yaml

server:
  port: ${PORT:8081}

cron:
  job: ${CRON_JOB:0 0 */6 * * *}

rss:
  url: ${RSS_URL:https://jobs.dou.ua/vacancies/feeds/?exp=1-3&remote&category=QA}